### ISSUE TITLE
Error when clicking on Max links

### ISSUE THREAD

**Issue by jdrowell** [wBanano/wban-dApp#102]
Ran into a small bug just now when supplying (on polygon, if it matters). Clicking on MAX as usual caused the page to reload. So I copied the amount and the I got "Not enough wBAN-wETH available!". Decrementing the last digit made it go through. Maybe truncate instead of rounding that value.

**Comment by wrap-that-potassium** [comment]
Max buttons for everything seem to be broken currently (e.g. also swapping ban to wban or withdrawing)

**Comment by wrap-that-potassium** [comment]
Turns out this is unrelated to rounding as there is no rounding done ;)
