### ISSUE TITLE
Invalid URL "Add Liquidity" button to Sushiswap on Polygon

### ISSUE THREAD

**Issue by Putdeksel** [wBanano/wban-dApp#106]
Page won't load due to changes on Sushiswap

**Comment by wrap-that-potassium** [comment]
Proper URL should be https://app.sushi.com/legacy/add/0xe20B9e246db5a0d21BF9209E4858Bc9A3ff7A034/0x7ceB23fD6bC0adD59E62ac25578270cFf1b9f619?chainId=137 now.

**Comment by wrap-that-potassium** [comment]
SushiSwap added redirects from old URLs to new ones.
Will deploy a fix to avoid those redirects though.
