### ISSUE TITLE
Display BAN price

### ISSUE THREAD

**Issue by wrap-that-potassium** [wBanano/wban-dApp#11]
... based on CoinGecko's API.

**Comment by thelamer** [comment]
https://api.coingecko.com/api/v3/simple/price?ids=banano&vs_currencies=usd
https://api.coingecko.com/api/v3/simple/price?ids=binancecoin&vs_currencies=usd
Pretty simple fetch and parse. 
Where do you want these, any place a number is mentioned ? IE:
```
0.13800  BNB ($77.56)
Balance: 10 BAN ($0.30)
```
