### ISSUE TITLE
Add info symbols/buttons (i) tooltips to crypto vocabulary like total supply

### ISSUE THREAD

**Issue by Beennnjo** [wBanano/wban-dApp#19]
Add little info symbols (i) to crypto related vocabulary. Could be a button to click or hover icon. I would place one for example besides the total supply statistic (top left hand info box). 
People could hover or click on the "i" to read what those numbers mean. This could help even if most number are selfexplanatory, not everybody knows their way around exchanges and crypto in general ....

**Comment by wrap-that-potassium** [comment]
@Beennnjo do you see any need for this besides the total supply?

**Comment by Beennnjo** [comment]
> @Beennnjo do you see any need for this besides the total supply?

So far, no. Maybe, if or when you are going to add other statistics.
