### ISSUE TITLE
Add Discord & Telegram links

### ISSUE THREAD

**Issue by thelamer** [wBanano/wban-dApp#25]
This is given Discord is the chosen community for this project. 
The app should have a link to the discord community along with README.md. 
Badge example for Labs Server:
```
https://img.shields.io/discord/710222836660437045.svg?color=ffff00&labelColor=555555&logoColor=ffffff&style=for-the-badge&label=Discord&logo=discord
```

**Comment by wrap-that-potassium** [comment]
Such link should be added to the About page.
