### ISSUE TITLE
Vue.js developer here. How to help ?

### ISSUE THREAD

**Issue by gkpo** [wBanano/wban-dApp#30]
Hi monkes,
I believe the success of this project will rely on every aspect of it. And the user interface is no exception.
I'm a 10+ years front-end / vue.js / react developer and I saw this app was using vue. So I'm willing to give some of my time if you guys need help. Here's what I could do:

- Work on some existing pages and tidy up, add slick animations, give it a smoother general feeling
- Make suggestions on some aspects of the user experience
- Create new pages that you guys still haven't made

Let me know,
Peace

**Comment by wrap-that-potassium** [comment]
DM me at "wrap-that-potassium" on Discord server :)
Closing this issue.
