### ISSUE TITLE
Let users get back their BAN if they reject the step 2 of the wBAN swap process

### ISSUE THREAD

**Issue by yekta** [wBanano/wban-dApp#53]
When the user is swapping BAN for wBAN, if they sign in the first step then reject the transaction, user's BAN stays in limbo. This shouldn't be the case since the user rejected the transaction. So the whole process can be cancellable after step 1 and before step 2.

**Comment by Battlesheep2** [comment]
This just happened to me, but as Gas required was too high. I could not complete the transaction. 100Ban out there somewhere.

**Comment by wrap-that-potassium** [comment]
Closing this issue mitigated by the swap button disabled when there is no BNB in the wallet.
