### ISSUE TITLE
Give users notice that adding additional funds to a farm will trigger a harvest

### ISSUE THREAD

**Issue by amamel** [wBanano/wban-dApp#70]
When supplying more SLP, wBAN balance is harvested and reset to zero without any notice of this occurring. Users should know that when depositing or withdrawing from the farm, it also harvests. 

Please add a notice below the farm that informs the user, that when they supply more LP to the farm, it will send the existing balance to Metamask. This is pretty terrifying to see your balance reset to zero without any notice that a harvest has occurred.

**Comment by wrap-that-potassium** [comment]
Adding tooltips on both "Supply" and "Withdraw" farm buttons:
![image](https://user-images.githubusercontent.com/83176631/133228908-6600ffb4-5cc0-4535-88f9-d6d9792549aa.png)
