### ISSUE TITLE
Action names not visible on mobile

### ISSUE THREAD

**Issue by mrexodia** [wBanano/wban-dApp#76]
![image](https://user-images.githubusercontent.com/2458265/144769102-ee2613af-9a4a-4381-b1d8-64488f8e2d84.png)

This was very confusing when trying to widthdraw some BAN.

I tracked it down to here, but I don't really know much about web development to see how this links to the codebase.

![image](https://user-images.githubusercontent.com/2458265/144769342-1659fb60-aa54-4ab0-ac6a-db7a8aba2183.png)

Perhaps primary and secondary need to be swapped here?

https://github.com/wBanano/wban-dApp/blob/fe1e6586e0009792857ac93b49c9d9bd190755c3/frontend/src/layouts/MainLayout.vue#L268-L271

**Comment by wrap-that-potassium** [comment]
That was indeed the problem!
Thanks. Will be released in the next version.
PS: sorry for the delay I don't know why GitHub isn't send me email notifications with new issues.

**Comment by mrexodia** [comment]
Might be in spam? The support is usually very helpful :)
