### ISSUE TITLE
BAN address in the setup page should be validated

### ISSUE THREAD

**Issue by wrap-that-potassium** [wBanano/wban-dApp#8]

**Comment by tigwyk** [comment]
I found an elegant one-liner regex for validating the address format, but it doesn't seem to prevent Vue from allowing the user to continue to the next step.

In Setup.vue, in the step for Banano Address, under the Banano Address q-input, I added:
`:rules="[val => val.match(/^ban_[13][0-13-9a-km-uw-z]{59}$/) || 'Invalid BAN address']"`

![image](https://user-images.githubusercontent.com/3312219/116011942-59a05500-a5dc-11eb-8f12-b152c8fbf36a.png)

This tries to match the filled-in value to the regex and it correctly pops up some text under the address field saying "Invalid BAN Address" if the formatting is wrong:
![image](https://user-images.githubusercontent.com/3312219/116011883-1940d700-a5dc-11eb-83a5-5e7c43ef0052.png)

Unfortunately I'm not sure how to make it so this validation failure actually halts the process. Right now, even if the user enters a badly formatted address they're still able to click "Continue" on this form.

**Comment by jeje** [comment]
Cool! I'll have a look at this and let you know what's missing.
I'll probably fix the font issue (color and size) of the error messages on this page as well.

**Comment by wrap-that-potassium** [comment]
Cool!
I'll have a look at this and let you know what's missing.
I'll probably fix the font issue (color and size) of the error messages on this page as well.

**Comment by wrap-that-potassium** [comment]
@tigwyk fyi, only a small amount of changes were needed on top of what you tried:
```vue
<q-form @submit="step = 2">
  <q-input
    v-model="banAddress"
    label="Banano Address"
    class="banano-address"
    dense
    autofocus
    :rules="[
      val => !!val || 'Banano address is required',
      val => val.match(/^ban_[13][0-13-9a-km-uw-z]{59}$/) || 'Invalid Banano address'
    ]"
  />
  <q-stepper-navigation>
    <q-btn type="submit" color="primary" text-color="black" label="Continue" />
  </q-stepper-navigation>
</q-form>
```

Mostly wrapping the `<q-input>` within a `<q-form>` and calling the "action" (`step = 2`) from the form submit instead of a click on the submit button.
