### ISSUE TITLE
Blank explorer URL when adding new network

### ISSUE THREAD

**Issue by benjiewheeler** [wBanano/wban-dApp#92]
When adding a network to metamask the block explorer URL field remains blank.

## Expected Behavior
The added network should have the block explorer URL field populated

## Current Behavior
The block explorer URL field remains blank

## Steps to Reproduce
1. Log into wBAN app on desktop.
2. Switch network (in the wBAN UI) to another one

(the new network must not be configured yet in metamask to trigger the "*Allow this site to add a network*" dialog window)

## Context (Environment)
**OS**: Zorin OS 16.1 (based on Ubuntu 20.04)
**Browser**: Google Chrome 100.0.4896.75
**Metamask**: 10.12.3

**Comment by wrap-that-potassium** [comment]
Opened a bug report in bnc-onboard library.
The library doesn't allow to specify the blockchain explorer url.
https://github.com/blocknative/web3-onboard/issues/948
